// SEARCH REDUCER
export const SEARCH_DATA_ARRAY = 'SEARCH_DATA_ARRAY';
export const CLEAR_SEARCH_HISTORY_ARRAY = 'CLEAR_SEARCH_HISTORY_ARRAY';
export const NEXT_PAGE_TOKEN = 'NEXT_PAGE_TOKEN';
export const CHANNEL_DATA = 'CHANNEL_DATA';

// FAVOURITES REDUCER
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';

// STATISTICS REDUCER
export const ADD_SEARCH_COUNT = 'ADD_SEARCH_COUNT';
export const SUM_OF_FOLLOWERS = 'SUM_OF_FOLLOWERS';
export const SUM_OF_VIDEOS_FETCHED = 'SUM_OF_VIDEOS_FETCHED';


